# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "gpunktblog"
license = "MIT"
licenselink = "https://github.com/gpunktschmitz/gpunktblog/blob/master/LICENSE"
description = "gpunktblog is the theme used for my blogs and is based on Anatole which is a beautiful minimalist two-column hugo theme based on farbox-theme-Anatole."
homepage = "https://github.com/gpunktschmitz/gpunktblog/"
demosite = "https://gpunktblog.gpunktschmitz.com/"
tags = ["blog", "responsive", "clean", "minimalist", "minimal", "personal"]
features = ["blog", "seo", "responsive", "mobile", "fontawesome"]
min_version = "0.53.0"

[author]
  name = "Guenther Schmitz"
  homepage = "https://www.gpunktschmitz.com"

# If porting an existing theme
[original]
  name = "Alexander Bilz"
  homepage = "https://alexbilz.com"
  repo = "https://github.com/lxndrblz/anatole/"
